import keymirror from 'keymirror';

export default keymirror({
    SET_ADDRESS: null,
    RECEIVE_ADDRESS_PREDICTIONS: null,
    RECEIVE_PLACE_PREDICTION: null,
    AUTOFILL_SELECT_NEXT: null,
    AUTOFILL_SELECT_PREV: null,
    SUBMIT_FORM: null,
    SUBMIT_FORM_SUCCESS: null,
    SUBMIT_FORM_ERROR: null,
    SELECT_OWNER_TYPE: null,
    SELECT_HOUSE_TYPE: null,
    SELECT_OWN_OR_RENT: null,
    SELECT_PARTY_FAVOR: null,
    SELECT_EXCITEMENT_LEVEL: null,
    SELECT_GIFT_TYPE: null,
    SELECT_CONGRATS_LEVEL: null,
    NEXT_STEP: null,
    PREVIOUS_STEP: null,
    SHOW_STREETVIEW_PREVIEW: null,
    VALIDATE_ADDRESS: null,
    VALIDATE_ADDRESS_SUCCESS: null,
    VALIDATE_ADDRESS_ERROR: null,
    CHOOSE_ADDRESS: null,
    LOAD_STEP: null,
    VIDEO_READY: null,
    SEND_EMAIL: null,
});
